package it.capone.entity;
// Generated 22-ago-2017 16.20.01 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "qax")
@NamedQueries({
	@NamedQuery(name="Categoria.findAll", query="SELECT c FROM Categoria c"),
	@NamedQuery(name="Categoria.findById", query="SELECT c FROM Categoria c WHERE c.idcategoria = :idcategoria"),
	@NamedQuery(name="Categoria.findByNome", query="SELECT c FROM Categoria c WHERE c.nome = :nome")
})
public class Categoria implements java.io.Serializable {

	private Integer idcategoria;
	private String nome;
	private Set<Domanda> domandas = new HashSet<Domanda>(0);

	public Categoria() {
	}

	public Categoria(String nome) {
		this.nome = nome;
	}

	public Categoria(String nome, Set<Domanda> domandas) {
		this.nome = nome;
		this.domandas = domandas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategoria", unique = true, nullable = false)
	public Integer getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(Integer idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Domanda> getDomandas() {
		return this.domandas;
	}

	public void setDomandas(Set<Domanda> domandas) {
		this.domandas = domandas;
	}

}
