package it.capone.entity;
// Generated 22-ago-2017 16.20.01 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentorisposta generated by hbm2java
 */
@Entity
@Table(name = "commentorisposta", catalog = "qax")
public class Commentorisposta implements java.io.Serializable {

	private Integer idcommentorisposta;
	private Risposta risposta;
	private Utente utente;
	private String descrizione;
	private Date datacreazione;

	public Commentorisposta() {
	}

	public Commentorisposta(Risposta risposta, String descrizione, Date datacreazione) {
		this.risposta = risposta;
		this.descrizione = descrizione;
		this.datacreazione = datacreazione;
	}

	public Commentorisposta(Risposta risposta, Utente utente, String descrizione, Date datacreazione) {
		this.risposta = risposta;
		this.utente = utente;
		this.descrizione = descrizione;
		this.datacreazione = datacreazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcommentorisposta", unique = true, nullable = false)
	public Integer getIdcommentorisposta() {
		return this.idcommentorisposta;
	}

	public void setIdcommentorisposta(Integer idcommentorisposta) {
		this.idcommentorisposta = idcommentorisposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrisposta", nullable = false)
	public Risposta getRisposta() {
		return this.risposta;
	}

	public void setRisposta(Risposta risposta) {
		this.risposta = risposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutente")
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "descrizione", nullable = false, length = 65535)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datacreazione", nullable = false, length = 19)
	public Date getDatacreazione() {
		return this.datacreazione;
	}

	public void setDatacreazione(Date datacreazione) {
		this.datacreazione = datacreazione;
	}

}
