package it.capone.entity;
// Generated 22-ago-2017 16.20.01 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentodomanda generated by hbm2java
 */
@Entity
@Table(name = "commentodomanda", catalog = "qax")
public class Commentodomanda implements java.io.Serializable {

	private Integer idcommentodomanda;
	private Domanda domanda;
	private Utente utente;
	private String descrizione;
	private Date datacreazione;

	public Commentodomanda() {
	}

	public Commentodomanda(Domanda domanda, String descrizione, Date datacreazione) {
		this.domanda = domanda;
		this.descrizione = descrizione;
		this.datacreazione = datacreazione;
	}

	public Commentodomanda(Domanda domanda, Utente utente, String descrizione, Date datacreazione) {
		this.domanda = domanda;
		this.utente = utente;
		this.descrizione = descrizione;
		this.datacreazione = datacreazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcommentodomanda", unique = true, nullable = false)
	public Integer getIdcommentodomanda() {
		return this.idcommentodomanda;
	}

	public void setIdcommentodomanda(Integer idcommentodomanda) {
		this.idcommentodomanda = idcommentodomanda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddomanda", nullable = false)
	public Domanda getDomanda() {
		return this.domanda;
	}

	public void setDomanda(Domanda domanda) {
		this.domanda = domanda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutente")
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "descrizione", nullable = false, length = 65535)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datacreazione", nullable = false, length = 19)
	public Date getDatacreazione() {
		return this.datacreazione;
	}

	public void setDatacreazione(Date datacreazione) {
		this.datacreazione = datacreazione;
	}

}
